package com.fh.entity.qizhe;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;

public class ProjectAuditHelper {

    public static Map<String, String> PROJECT_INFO = new LinkedHashMap<>();

    public static Map<String, String> UPPER_CASE_INFO = new HashMap<>();

    public static Map<String, String> PROJECT_HELP = new HashMap<>();

    static {
        PROJECT_INFO.put("a01", "未设置“加油站6S+管理”文件盒（F-01），扣1分");
        PROJECT_INFO.put("a02", "定置管理图册未放置在“加油站6S+管理”文件盒里，扣1分");
        PROJECT_INFO.put("a03", "红单物品未集中存放，扣1分");
        PROJECT_INFO.put("a04", "无卫生管理责任制或部分区域管理责任不明确，扣1分");
        PROJECT_INFO.put("a05", "无定置管理图册，扣20分");
        PROJECT_INFO.put("a06", "办公室、收银区、便利店、加油现场（含站房四周）、配发电间、厨房餐厅、员工宿舍、活动室、卫生间、其它房间定置管理图册缺项，每项扣2分");
        PROJECT_INFO.put("a07", "实际摆放物品（一级清单可移动物品）与定置管理图不符（正在使用的除外），或未按定位标识摆放，每个区域（房间）扣1分");
        PROJECT_INFO.put("a08", "站内室外或室内出现过期海报，扣1分（2分封顶）");
        PROJECT_INFO.put("a09", "站内海报框外粘贴海报，或收银区、文件柜等设施设备上随意粘贴便条、价签等，每处扣1分（3分封顶）");
        PROJECT_INFO.put("a10", "设施设备不完好（锈蚀、损坏、墙面涂料剥落等），每件（处）扣1分（3分封顶）");
        PROJECT_INFO.put("a11", "站内各区域、设施设备、商品等不整洁（有明显垃圾、积尘、积水、油污、污渍、蛛网，墙面明显污损），每处扣1分（3分封顶）");
        PROJECT_INFO.put("a12", "6S标识标牌制作不规范，每样扣１分（3分封顶）");
        PROJECT_INFO.put("a13", "6S标识标牌安装使用不规范，每样扣１分（3分封顶）");
        PROJECT_INFO.put("a14", "6S标识标牌损坏未及时修护，每样扣１分（3分封顶）");
        PROJECT_INFO.put("a15", "手机未设集中放置位置，未粘贴定位标识，实际未落实集中管理，摆放无序，扣1分");
        PROJECT_INFO.put("a16", "茶杯未设集中放置位置，未粘贴定位标识，实际未落实集中管理，摆放无序，扣1分");
        PROJECT_INFO.put("a17", "书架无分类标识牌，书籍无分类标签，或书籍摆放零乱或与分类标识牌不符，扣1分");
        PROJECT_INFO.put("a18", "存档资料未放入档案盒，或档案盒未填写资料日期和目录，扣1分");
        PROJECT_INFO.put("a19", "存档小票未整理保存，保存的小票未填写日期，扣1分");
        PROJECT_INFO.put("a20", "电源开关上方未粘贴“请随手关灯”提示牌，扣1分");
        PROJECT_INFO.put("a21", "两个或以上按键的电源开关未粘贴按键控制标识或标识不易识别，扣1分");
        PROJECT_INFO.put("a22", "安装空调的房间未安装遥控板插袋，或有插袋无遥控板，扣1分");
        PROJECT_INFO.put("a23", "空调遥控板插袋上方未粘贴“请随手关空调”提示牌，扣1分");
        PROJECT_INFO.put("a24", "无人时未关空调，扣2分");
        PROJECT_INFO.put("a25", "水龙头上方未粘贴“请节约用水”提示牌，扣1分");
        PROJECT_INFO.put("a26", "窗帘未粘贴开启线，或开启时未按标线开启，扣1分");
        PROJECT_INFO.put("a27", "站房（室内）灭火器设置不符合要求，未粘贴定位标识，扣1分");
        PROJECT_INFO.put("a28", "站房内有较明显高低差或存在安全隐患的门槛、台阶，服务区与办公区需提示顾客止步或其它需要提醒的地方未粘贴安全警示线，扣1分");
        PROJECT_INFO.put("a29", "设备线路零乱，接线不规范，每处扣1分（3分封顶）");
        PROJECT_INFO.put("a30", "设备安装后较长的电源线路未作绕圈处理，扣1分");
        PROJECT_INFO.put("a31", "顾客视线范围内（含办公室）的电源线、信号线、管线等未作隐蔽处理，扣1分");
        PROJECT_INFO.put("a32", "信息设备、空调、热水器、洗衣机、电视机等设备的电源线、信号线、管道（线）未隐蔽设置的，扣1分");
        PROJECT_INFO.put("b01", "加油现场未按《加油站细节管理手册》要求摆放物品，扣1分");
        PROJECT_INFO.put("b02", "无站铭牌或制作不规范，扣2分");
        PROJECT_INFO.put("b03", "新版站铭牌星级、支付方式和便民服务标识牌与实际不符或摆放位置不正确，扣1分");
        PROJECT_INFO.put("b04", "安装新版站铭牌的，未取消原报警监控和95504温馨提示牌，扣1分");
        PROJECT_INFO.put("b05", "便利店前未配置不锈钢垃圾桶，扣1分");
        PROJECT_INFO.put("b06", "便利店前仍放置废旧电池回收箱，扣1分");
        PROJECT_INFO.put("b07", "便利店前物品、室外垃圾桶未按要求设置地面定位标识，扣1分");
        PROJECT_INFO.put("b08", "促销展区未设置地面定位标识，扣1分");
        PROJECT_INFO.put("b09", "垃圾桶未按要求粘贴限高线，扣1分");
        PROJECT_INFO.put("b10", "垃圾桶内垃圾超过限高线未及时清理，扣1分");
        PROJECT_INFO.put("b11", "摩托车加油处未按标准配置灭火器、加油壶、置物架、遮阳伞、提示牌，扣1分");
        PROJECT_INFO.put("b12", "摩托车加油区域未按要求用黄色标线标示，扣1分");
        PROJECT_INFO.put("b13", "一层进入办公楼的门未设置开闭线，扣1分");
        PROJECT_INFO.put("b14", "计量器具箱未放置在卸油区消防器材间，扣1分（询问该物品放置位置，再评判）");
        PROJECT_INFO.put("b15", "绿化地、盆栽有杂物、杂草，枯枝未清理，扣1分");
        PROJECT_INFO.put("b16", "站前绿化植物高度高于1米，扣1分");
        PROJECT_INFO.put("b17", "在顾客可见范围内晾晒衣服，扣1分");
        PROJECT_INFO.put("b18", "一楼保洁用品（具）未集中管理，每处扣1分");
        PROJECT_INFO.put("b19", "清洁用具未按要求设置标识牌，或放置地面的清洁用具无地面定位标线，扣1分");
        PROJECT_INFO.put("b20", "拖把、抹布未用颜色区分或颜色不符，扣1分");
        PROJECT_INFO.put("b21", "污水井、生化池、雨水井、消防井、电力、燃气管道井井盖未按要求涂刷相应颜色的油漆，或未标出介质流向，扣1分");
        PROJECT_INFO.put("b22", "硬化地面下埋设的油品、电缆管道未按要求在地面上进行标示的，扣3分");
        PROJECT_INFO.put("b23", "硬化地面下埋设的油品、电缆管道在地面有标识，但变向处或无变向未按5米设置一组标识的，扣2分");
        PROJECT_INFO.put("b24", "室外其它区域物品堆放凌乱，无地面标线，扣1分");
        PROJECT_INFO.put("c01", "办公室整体布局不合理（一般设置机柜、办公桌、桌柜、配套座椅、文件柜、灭火器、垃圾桶），扣1分");
        PROJECT_INFO.put("c02", "电脑主机放置不合理，扣1分");
        PROJECT_INFO.put("c03", "清洁抹布未隐蔽设置，扣1分");
        PROJECT_INFO.put("c04", "人离座时办公椅未按要求摆放，扣1分");
        PROJECT_INFO.put("c05", "办公桌抽屉未粘贴分类标识牌或未按要求设置，扣1分");
        PROJECT_INFO.put("c06", "办公桌抽屉内物品与分类标识牌不符，扣1分");
        PROJECT_INFO.put("c07", "办公桌抽屉内办公文具未使用收纳格或行迹管理，或文件资料分散放置，扣1分");
        PROJECT_INFO.put("c08", "文件柜（标准文件柜）分类标牌未按要求设置，扣1分");
        PROJECT_INFO.put("c09", "文件柜（标准文件柜）上层文件资料未统一装入文件盒，扣1分");
        PROJECT_INFO.put("c10", "文件柜内存放非当年有效文件资料，扣1分");
        PROJECT_INFO.put("c11", "文件柜（标准文件柜）下层未放置办公用品或其它地方摆放备用办公用品，扣1分");
        PROJECT_INFO.put("c12", "文件柜（标准文件柜）下层物品未分类整齐摆放，未使用收纳格或蓝色标线区分，扣1分");
        PROJECT_INFO.put("c13", "文件柜（标准文件柜）下层物品无分类标签，或实际摆放与分类标签不符，扣1分");
        PROJECT_INFO.put("c14", "文件柜（标准文件柜）内二级清单填写不规范、粘贴不规范或与实际不符，扣1分");
        PROJECT_INFO.put("c15", "文件盒内三级清单填写不规范、粘贴不规范或与实际不符，扣1分");
        PROJECT_INFO.put("c16", "文件盒、文件夹无标签或制作不规范，扣1分");
        PROJECT_INFO.put("c17", "桌柜内放置的常用工具、备用清洁用品或其它物品未分类整齐摆放，未使用蓝色标线区分（采用行迹管理的除外），扣1分");
        PROJECT_INFO.put("c18", "桌柜内物品无分类标签，或实际摆放与分类标签不符，扣1分");
        PROJECT_INFO.put("c19", "办公室门把手上方无“推”“拉”标识牌，扣1分");
        PROJECT_INFO.put("c20", "办公室的门未粘贴开闭线，扣1分");
        PROJECT_INFO.put("c21", "办公桌摆放物品定位标识不全，扣1分");
        PROJECT_INFO.put("c22", "钥匙箱内分区挂放位置、颜色不正确，钥匙牌或内芯背景色不正确，扣1分");
        PROJECT_INFO.put("c23", "便民医药箱设置位置不合理，未粘贴定位标识，扣1分");
        PROJECT_INFO.put("c24", "加油站信息设备配置超标准，每件扣1分");
        PROJECT_INFO.put("c25", "办公桌设备开孔穿线不合理或线路整理不规范，显零乱，扣1分");
        PROJECT_INFO.put("c26", "办公桌设备电源线标签不全，扣1分");
        PROJECT_INFO.put("c27", "零管设备与监控设备未整合摆放入机柜内，扣1分");
        PROJECT_INFO.put("c28", "机柜内设备线路整理不规范，显零乱，扣1分");
        PROJECT_INFO.put("c29", "机柜内显示器、键盘、鼠标无定位标识，扣1分");
        PROJECT_INFO.put("c30", "机柜内网线标签、电源线标签、设备标签不全，扣1分");
        PROJECT_INFO.put("c31", "机柜底部未铺设绝缘垫，或边沿未张贴安全警示线，扣1分");
        PROJECT_INFO.put("d01", "桌面设备、糖果架、桌贴广告、签字笔、资料架、公告牌、提示牌、购物袋等设置不合理，显零乱的，每处扣1分（3分封顶）");
        PROJECT_INFO.put("d02", "收银设备不全，如无小票打印机、无收银钱箱等，扣1分");
        PROJECT_INFO.put("d03", "收银区未设置打印、复印一体机，扣1分");
        PROJECT_INFO.put("d04", "收银POS机客显被遮挡，扣1分");
        PROJECT_INFO.put("d05", "两个银行卡密码键盘放置在一起（不易识别），扣1分");
        PROJECT_INFO.put("d06", "宣传资料散放，资料架规格不符，扣1分");
        PROJECT_INFO.put("d07", "收银区摆放垃圾桶，扣1分");
        PROJECT_INFO.put("d08", "收银区抽屉、柜门未粘贴分类标识牌，扣1分");
        PROJECT_INFO.put("d09", "收银区抽屉、柜内物品与分类标识牌不符，扣1分");
        PROJECT_INFO.put("d10", "收银区抽屉、柜内物品未分类整齐摆放，每处扣1分");
        PROJECT_INFO.put("d11", "文件盒、文件夹无标签或制作不规范，扣1分");
        PROJECT_INFO.put("d12", "收银区台面台柜的物品定位标识不全，扣1分");
        PROJECT_INFO.put("d13", "收银台背柜摆放非油商品以外的物品，扣1分");
        PROJECT_INFO.put("d14", "自助服务终端机线路未整理、零乱，或未设置规范的操作说明，扣1分");
        PROJECT_INFO.put("d15", "收银台台面设备开孔穿线不合理或线路整理不规范，显零乱，扣1分");
        PROJECT_INFO.put("d16", "收银台下方可视线路未进入线槽，扣1分");
        PROJECT_INFO.put("d17", "收银台下电源板后方线路未整理，显零乱，扣1分");
        PROJECT_INFO.put("d18", "收银台下方电源面板背面未加装保护盖，扣2分");
        PROJECT_INFO.put("d19", "放置主机的柜门未设置百叶窗通风口，扣1分");
        PROJECT_INFO.put("d20", "收银台下方面板处网线标签、电源线标签不全，扣1分");
        PROJECT_INFO.put("e01", "加油站营业期间，便利店内的照明设备未按要求开启，扣1分");
        PROJECT_INFO.put("e02", "便利店商品价签不规范的扣1分");
        PROJECT_INFO.put("e03", "便利店商品未正面向外的扣1分");
        PROJECT_INFO.put("e04", "便利店商品与上层隔板间距过大或过小扣1分");
        PROJECT_INFO.put("e05", "货架陈列过期商品，扣5分");
        PROJECT_INFO.put("e06", "商品严重缺货，扣3分");
        PROJECT_INFO.put("e07", "食品类非油商品直接放置地面，扣1分");
        PROJECT_INFO.put("e08", "室内堆头陈列不规范，靠墙堆头首层未割箱陈列等，扣1分");
        PROJECT_INFO.put("e09", "便利店门口两侧地堆过高，遮挡玻窗，托盘不统一、摆放不整齐，扣1分");
        PROJECT_INFO.put("e10", "岛上堆头围挡不整洁，商品摆放不整齐，无相应的价签或pop、爆炸卡宣传标识，扣1分");
        PROJECT_INFO.put("e11", "快餐区柜内物品摆放不整齐，扣1分");
        PROJECT_INFO.put("e12", "便利店内摆放与非油业务无关的物品（集中存放的员工手机、水杯除外），扣2分");
        PROJECT_INFO.put("e13", "店内购物篮、购物车未定置摆放，或无地面标线，扣1分");
        PROJECT_INFO.put("e14", "库房乱堆乱放未分区存储的，扣1分");
        PROJECT_INFO.put("e15", "库房食品类货品直接放置于地面的，扣1分");
        PROJECT_INFO.put("e16", "库房未制作分区牌，且分区牌所指区域与实际分区不符的，扣1分");
        PROJECT_INFO.put("e17", "库房货品下方无磁性拔码器标识牌，扣1分");
        PROJECT_INFO.put("e18", "库房货品磁性拔码器标识牌信息不全，扣1分");
        PROJECT_INFO.put("e19", "开展快餐业务的，熟食类商品无熟食管控表，粘贴不规范，扣1分");
        PROJECT_INFO.put("e20", "库房未设置过期/损坏商品区、退/换商品区、非入库赠品区（有此类赠品须设置），每项扣1分");
        PROJECT_INFO.put("e21", "库房过期/损坏商品区、退/换商品区、非入库赠品区（有此类赠品须设置），未用相应颜色区分，且未设置对应管控表，每项扣1分");
        PROJECT_INFO.put("e22", "放置库房的促销物料散乱、无“促销物料暂存区”标识，扣1分");
        PROJECT_INFO.put("e23", "未使用或过期的促销物料，任意堆放在加油现场，扣1分");
        PROJECT_INFO.put("e24", "未设置非油商品现场卸货区的，扣1分");
        PROJECT_INFO.put("e25", "放置开水壶的台面、咖啡机、开水机未粘贴“当心高温”安全标识，扣1分");
        PROJECT_INFO.put("e26", "便利店吧台台面物品摆放零乱，或无定位标识，或无地面标线，或无座椅，扣1分");
        PROJECT_INFO.put("e27", "便民工具箱未放置在便利店内，未粘贴定位标识，扣1分");
        PROJECT_INFO.put("f01", "餐厅餐椅未使用时未归位，扣1分");
        PROJECT_INFO.put("f02", "消毒柜未按要求粘贴物品摆放示意图，扣1分");
        PROJECT_INFO.put("f03", "厨房操作台台面物品摆放不整齐，扣1分");
        PROJECT_INFO.put("f04", "调味瓶、调料盒无相应标签，扣1分");
        PROJECT_INFO.put("f05", "生食、熟食用砧板未按要求分开使用，扣1分");
        PROJECT_INFO.put("f06", "橱柜柜门、收纳盒未粘贴相应的分类标牌标签，扣1分");
        PROJECT_INFO.put("f07", "橱柜柜内盒内摆放物品零乱或与分类标识不符，扣1分");
        PROJECT_INFO.put("f08", "用餐后未及时清洗碗筷，餐后未及时清倒垃圾，扣1分");
        PROJECT_INFO.put("f09", "厨师用劳保用品、保洁用品未按要求集中放置，或未粘贴相应标识牌，扣１分");
        PROJECT_INFO.put("f10", "生活区扫把、撮箕、垃圾桶未摆放在固定位置，或未粘贴物品定位图标、定位标线，扣1分");
        PROJECT_INFO.put("f11", "橱柜、冰箱、消毒柜内部不清洁，扣1分");
        PROJECT_INFO.put("f12", "换气扇、抽油烟机油污重，扣1分");
        PROJECT_INFO.put("f13", "拖把挂放处未粘贴清洁用具分类标牌，扣1分");
        PROJECT_INFO.put("f14", "拖把未用颜色区分或颜色不符，扣1分");
        PROJECT_INFO.put("f15", "员工衣柜、鞋柜配置超标，扣1分");
        PROJECT_INFO.put("f16", "床位空置，被子叠放不整齐，床上用品不统一，扣1分");
        PROJECT_INFO.put("f17", "员工柜内、抽屉内物品摆放不规范，显零乱，扣1分");
        PROJECT_INFO.put("f18", "鞋柜内放置的鞋摆放不整齐，扣1分");
        PROJECT_INFO.put("f19", "员工衣柜、鞋柜、毛巾架、毛巾、面盆的员工编号不全，扣1分");
        PROJECT_INFO.put("f20", "寝室内椅子未使用时未归位，扣1分");
        PROJECT_INFO.put("f21", "桌面物品、面盆架、垃圾桶未粘贴定位标识，扣1分");
        PROJECT_INFO.put("f22", "淋浴间喷淋水龙头正上方未粘贴冷热水管标识，扣1分");
        PROJECT_INFO.put("f23", "房间内物品整体摆放不整齐，每个房间扣1分");
        PROJECT_INFO.put("g01", "未按要求设置卫生间指示牌，扣1分");
        PROJECT_INFO.put("g02", "未按要求粘贴“推”“拉”“禁止吸烟”“请节约用纸”标识牌，扣1分");
        PROJECT_INFO.put("g03", "提示牌不全，扣1分");
        PROJECT_INFO.put("g04", "无巡查牌，扣1分");
        PROJECT_INFO.put("g05", "巡查记录提前或延迟记录，扣1分");
        PROJECT_INFO.put("g06", "自助加油站未配置洗手液或安装不规范，扣1分");
        PROJECT_INFO.put("g07", "盥洗间未设置不锈钢垃圾桶，扣2分");
        PROJECT_INFO.put("g08", "盥洗间不锈钢垃圾桶未粘贴限高线、或无定位标识，扣1分");
        PROJECT_INFO.put("g09", "无A字形告示牌或未清洁厕所时未摆放在洗手台下方左侧，扣1分");
        PROJECT_INFO.put("g10", "小便池未放置防溅垫、除臭丸（樟脑球），扣1分");
        PROJECT_INFO.put("g11", "蹲位前台阶未粘贴“当心台阶”安全标识或粘贴不全，扣1分");
        PROJECT_INFO.put("g12", "蹲位隔板上未安装衣帽钩，扣1分");
        PROJECT_INFO.put("g13", "厕所蹲位设置物品放置盒（架）的，未粘贴“请带好随身物品”标识，扣1分");
        PROJECT_INFO.put("g14", "蹲位无垃圾篓，或摆放位置不一致，扣1分");
        PROJECT_INFO.put("g15", "洁厕刷（马桶刷）未按要求放置，扣1分");
        PROJECT_INFO.put("g16", "洗手台排水管零乱，扣1分");
        PROJECT_INFO.put("g17", "卫生间上锁或封闭，特殊情况未张贴告示告知开放时间，扣2分");
        PROJECT_INFO.put("g18", "设施不完好，扣1分");
        PROJECT_INFO.put("g19", "有异味、有污垢，扣2分");
        PROJECT_INFO.put("g20", "有积水、有积尘、有蛛网，扣2分");

        for (String key : PROJECT_INFO.keySet()) {
            UPPER_CASE_INFO.put(key, key.toUpperCase());
        }


    /*    PROJECT_HELP.put("a01", "　");
        PROJECT_HELP.put("a02", "　");
        PROJECT_HELP.put("a03", "　一定时期后应全部清除加油站");
        PROJECT_HELP.put("a04", "　暂不考核");
        PROJECT_HELP.put("a05", "可用A4纸黑白打印装订成册　");
        PROJECT_HELP.put("a06", "先期考核办公室、加油现场（含站房四周）、配发电间、厨房餐厅、员工宿舍、活动室，2018年7月起全面考核　");
        PROJECT_HELP.put("a07", "先期考核办公室、加油现场（含站房四周）、配发电间、厨房餐厅、员工宿舍、活动室，2018年7月起全面考核　");
        PROJECT_HELP.put("a08", "　");
        PROJECT_HELP.put("a09", "　暂不考核，规范后考核");
        PROJECT_HELP.put("a10", "其它项有考核的除外　");
        PROJECT_HELP.put("a11", "重点关注顾客可视的加油现场、加油设备、主立牌灯箱、罩棚、立柱、墙面、绿化等，其它项有考核的除外　");
        PROJECT_HELP.put("a12", "　暂不考核，2018年7月起全面考核");
        PROJECT_HELP.put("a13", "　暂不考核，2018年7月起全面考核");
        PROJECT_HELP.put("a14", "　");
        PROJECT_HELP.put("a15", "　");
        PROJECT_HELP.put("a16", "　办公室可放置在个人物品柜里，加油现场可根据需要设置物品整理箱");
        PROJECT_HELP.put("a17", "　");
        PROJECT_HELP.put("a18", "　备用帐表册可叠放，不用放于档案盒");
        PROJECT_HELP.put("a19", "　");
        PROJECT_HELP.put("a20", "一组电源开关一个　");
        PROJECT_HELP.put("a21", "　");
        PROJECT_HELP.put("a22", "　便利店内可安装在柜门内侧");
        PROJECT_HELP.put("a23", "　");
        PROJECT_HELP.put("a24", "　");
        PROJECT_HELP.put("a25", "卫生间洗手盆的水龙头已粘贴“请节约用水”提示的除外　");
        PROJECT_HELP.put("a26", "左右开启的窗帘不设开启线，但开启状态应统一　");
        PROJECT_HELP.put("a27", "　");
        PROJECT_HELP.put("a28", "粘贴在高处，粘贴方式需优化　");
        PROJECT_HELP.put("a29", "　其它项有考核的除外");
        PROJECT_HELP.put("a30", "　");
        PROJECT_HELP.put("a31", "初期室内未作隐蔽处理，但只有一个线槽的考核　");
        PROJECT_HELP.put("a32", "暂不考核，适用于2017年及以后新建投运或实施站房技改的加油站　");
        PROJECT_HELP.put("b01", "参照细节管理手册，侧重加油岛和标准物件，垃圾桶不需要每岛一个　");
        PROJECT_HELP.put("b02", "暂不考核，2018年5月20日起全面考核　");
        PROJECT_HELP.put("b03", "　暂不考核，2018年5月20日起全面考核");
        PROJECT_HELP.put("b04", "　暂不考核，2018年5月20日起全面考核");
        PROJECT_HELP.put("b05", "直径约30cm为宜，分公司内统一型号，不具备条件的可不配置　");
        PROJECT_HELP.put("b06", "先期考核办公室、加油现场（含站房四周）、配发电间、厨房餐厅、员工宿舍、活动室，2018年7月起全面考核　");
        PROJECT_HELP.put("b07", "绿植除外　");
        PROJECT_HELP.put("b08", "　");
        PROJECT_HELP.put("b09", "　便利店前、加油现场");
        PROJECT_HELP.put("b10", "暂不考核　");
        PROJECT_HELP.put("b11", "加油枪直接向摩托车加油的除外　");
        PROJECT_HELP.put("b12", "　加油枪直接向摩托车加油的除外");
        PROJECT_HELP.put("b13", "　");
        PROJECT_HELP.put("b14", "　");
        PROJECT_HELP.put("b15", "　");
        PROJECT_HELP.put("b16", "　暂不考核");
        PROJECT_HELP.put("B17", "结合实际情况评判是否扣分　");
        PROJECT_HELP.put("b18", "　厕所设置在便利店内的，厕所内可适量设置拖把");
        PROJECT_HELP.put("b19", "　");
        PROJECT_HELP.put("b20", "　");
        PROJECT_HELP.put("b21", "　");
        PROJECT_HELP.put("b22", "　暂不考核，适用于2017年及以后新建投运或实施管线改造的加油站");
        PROJECT_HELP.put("b23", "　暂不考核，适用于2017年及以后新建投运或实施管线改造的加油站");
        PROJECT_HELP.put("b24", "尽量掩蔽，不宜多设　");
        PROJECT_HELP.put("c01", "办公桌一般不超过3张；一楼设置办公室的，二楼一般不再设置　");
        PROJECT_HELP.put("c02", "　");
        PROJECT_HELP.put("c03", "　一定时期后应全部清除加油站");
        PROJECT_HELP.put("c04", "");
        PROJECT_HELP.put("c05", "从上到下一般为“办公文具”“常用文件”“个人物品”，按需设置　");
        PROJECT_HELP.put("c06", "　");
        PROJECT_HELP.put("c07", "");
        PROJECT_HELP.put("c08", "　上层“文件资料”，下层“办公用品”");
        PROJECT_HELP.put("c09", "有三层的，最下面一层可设置资料篮，整齐放置待装订资料");
        PROJECT_HELP.put("c10", "暂不考核，有特殊要求的除外　");
        PROJECT_HELP.put("c11", "其它地方摆放办公用品的暂不考核，2019年1月1日起执行考核　");
        PROJECT_HELP.put("c12", "　多余空间可放置备用账表册");
        PROJECT_HELP.put("c13", "　与标签不符暂不考核，需完善分类优化");
        PROJECT_HELP.put("c14", "其它文件柜不设置二级清单　");
        PROJECT_HELP.put("c15", "　");
        PROJECT_HELP.put("c16", "　文件夹可用A4纸长边制作");
        PROJECT_HELP.put("c17", "备用清洁用品、常用工具不得放置在文件柜内（防爆电筒除外），不首选设置在办公室内（无条件的除外）　");
        PROJECT_HELP.put("c18", "　不设置二级清单");
        PROJECT_HELP.put("c19", "　");
        PROJECT_HELP.put("c20", "二楼办公室不粘贴，便利店库房不粘贴　");
        PROJECT_HELP.put("c21", "桌面物品、主机箱　");
        PROJECT_HELP.put("c22", "　");
        PROJECT_HELP.put("c23", "方便实用就可以　");
        PROJECT_HELP.put("c24", "暂不考核　");
        PROJECT_HELP.put("c25", "　");
        PROJECT_HELP.put("c26", "　");
        PROJECT_HELP.put("c27", "　键盘、鼠标、显示器共用");
        PROJECT_HELP.put("c28", "　");
        PROJECT_HELP.put("c29", "　");
        PROJECT_HELP.put("c30", "　");
        PROJECT_HELP.put("c31", "");
        PROJECT_HELP.put("d01", "提出优化建议　");
        PROJECT_HELP.put("d02", "　台面下不能放置收银钱箱的可用抽屉，尽量不取消");
        PROJECT_HELP.put("d03", "　");
        PROJECT_HELP.put("d04", "");
        PROJECT_HELP.put("d05", "　");
        PROJECT_HELP.put("d06", "　");
        PROJECT_HELP.put("d07", "");
        PROJECT_HELP.put("d08", "　提出优化建议（保险柜、非油商品、收银钱箱不粘贴？）");
        PROJECT_HELP.put("d09", "");
        PROJECT_HELP.put("d10", "需细化描述　");
        PROJECT_HELP.put("d11", "文件夹标签可用A4纸长边制作　");
        PROJECT_HELP.put("d12", "　");
        PROJECT_HELP.put("d13", "　有必要设置的设备除外");
        PROJECT_HELP.put("d14", "　");
        PROJECT_HELP.put("d15", "　");
        PROJECT_HELP.put("d16", "　");
        PROJECT_HELP.put("d17", "　");
        PROJECT_HELP.put("d18", "　");
        PROJECT_HELP.put("d19", "　");
        PROJECT_HELP.put("d20", "　");
        PROJECT_HELP.put("e01", "广告灯箱光源须全时段开启；8点至17点59分，光线充足的站，吊顶灯须开启50%以上；18点至第二天7点59分，吊顶灯须全部开启；有报修记录的除外　");
        PROJECT_HELP.put("e02", "在顾客能够触及到地方，所放置的商品均应用于销售，为此，必须要明码标价（有价签或POP/爆炸卡均可），且价签须靠左陈列。　");
        PROJECT_HELP.put("e03", "　商品的正面应面向顾客。");
        PROJECT_HELP.put("e04", "为保证商品的丰满和量感陈列，以及易于顾客取拿的原则，加油站应主动调整货架层板与商品的间距，保持不少于二指的高度和不多于三到四指的高度。");
        PROJECT_HELP.put("e05", "");
        PROJECT_HELP.put("e06", "普通货架每90公分货架长度，缺货超过30公分，视为严重缺货。回型货架单个层板缺货超过一半，视为严重缺货。　");
        PROJECT_HELP.put("e07", "");
        PROJECT_HELP.put("e08", "室内堆头原则上总高度不超过0.8米，如有特殊陈列须向公司报备，有报备手续的除外。靠壁堆头首层须割箱陈列。");
        PROJECT_HELP.put("e09", "原则不得遮挡橱窗玻璃，地堆高度0.8米为宜，高于1米的视为过高。");
        PROJECT_HELP.put("e10", "针对岛上有堆头加油站进行考核　");
        PROJECT_HELP.put("e11", "针对有快餐区的加油站　");
        PROJECT_HELP.put("e12", "　标准店及高级店纳入考核，顾客目视可及的地方均纳入考核范围，可放置促销赠品");
        PROJECT_HELP.put("e13", "　针对有购物篮、购物车的加油站");
        PROJECT_HELP.put("e14", "　");
        PROJECT_HELP.put("e15", "　");
        PROJECT_HELP.put("e16", "　");
        PROJECT_HELP.put("e17", "磁性拨码器是用来方便库房计算进出货数量品种、盘库用的　");
        PROJECT_HELP.put("e18", "　");
        PROJECT_HELP.put("e19", "针对开展快餐业务的加油站，应在熟食类商品存储区域张贴管控表　");
        PROJECT_HELP.put("e20", "非入库赠品指非卖品赠品。　");
        PROJECT_HELP.put("e21", "　");
        PROJECT_HELP.put("e22", "　");
        PROJECT_HELP.put("e23", "　");
        PROJECT_HELP.put("e24", "　");
        PROJECT_HELP.put("e25", "　");
        PROJECT_HELP.put("e26", "　");
        PROJECT_HELP.put("e27", "无便利店的放置在办公室适当位置");
        PROJECT_HELP.put("f01", "　");
        PROJECT_HELP.put("f02", "　");
        PROJECT_HELP.put("f03", "　不要求粘贴定位标识标线");
        PROJECT_HELP.put("f04", "");
        PROJECT_HELP.put("f05", "");
        PROJECT_HELP.put("f06", "　");
        PROJECT_HELP.put("f07", "");
        PROJECT_HELP.put("f08", "");
        PROJECT_HELP.put("f09", "");
        PROJECT_HELP.put("f10", "　");
        PROJECT_HELP.put("f11", "　");
        PROJECT_HELP.put("f12", "");
        PROJECT_HELP.put("f13", "　");
        PROJECT_HELP.put("f14", "　");
        PROJECT_HELP.put("f15", "　暂不考核");
        PROJECT_HELP.put("f16", "　参照细节管理手册");
        PROJECT_HELP.put("f17", "随机抽查两名现场当班员工的员工柜　");
        PROJECT_HELP.put("f18", "　");
        PROJECT_HELP.put("f19", "　");
        PROJECT_HELP.put("f20", "　");
        PROJECT_HELP.put("f21", "　");
        PROJECT_HELP.put("f22", "　");
        PROJECT_HELP.put("f23", "　主要针对未明确考核标准的区域");
        PROJECT_HELP.put("g01", "　90度指示牌仅用于厕所不醒目的站");
        PROJECT_HELP.put("g02", "　");
        PROJECT_HELP.put("g03", "　五种提示牌");
        PROJECT_HELP.put("g04", "");
        PROJECT_HELP.put("g05", "");
        PROJECT_HELP.put("g06", "暂不考核　");
        PROJECT_HELP.put("g07", "直径约30cm为宜，分公司内统一型号");
        PROJECT_HELP.put("g08", "");
        PROJECT_HELP.put("g09", "");
        PROJECT_HELP.put("g10", "　");
        PROJECT_HELP.put("g11", "　");
        PROJECT_HELP.put("g12", "");
        PROJECT_HELP.put("g13", "　");
        PROJECT_HELP.put("g14", "　");
        PROJECT_HELP.put("g15", "　");
        PROJECT_HELP.put("g16", "　重点检查可视部分");
        PROJECT_HELP.put("g17", "　");
        PROJECT_HELP.put("g18", "　");
        PROJECT_HELP.put("g19", "　");
        PROJECT_HELP.put("g20", "　");*/

    }
}
